apiVersion: v1
kind: Service
metadata:
  name: docgen-minio
  namespace: docgen
spec:
  type: ClusterIP
  selector:
    app: docgen-minio
  ports:
    - name: api
      port: 9000
      targetPort: 9000
    - name: console
      port: 9001
      targetPort: 9001
