package com.docgen.property;

import com.docgen.service.SegmentService;
import com.docgen.repository.SegmentRepository;
import com.docgen.repository.SegmentTagMappingRepository;
import com.docgen.repository.SegmentVersionRepository;
import com.docgen.service.AuditLogService;
import com.docgen.service.DependencyGraphService;
import com.docgen.service.SegmentVersionService;
import io.minio.MinioClient;
import net.jqwik.api.*;

import javax.xml.parsers.DocumentBuilderFactory;
import java.io.ByteArrayInputStream;
import java.lang.reflect.Method;
import java.util.*;
import java.util.zip.ZipEntry;
import java.util.zip.ZipInputStream;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.mock;

/**
 * Property-based tests for empty .docx generation in SegmentService.
 *
 * <p><b>Validates: Requirements 7.2</b></p>
 *
 * <p>Verifies that generateEmptyDocx() always produces a valid Open XML ZIP structure
 * regardless of segment name input, and that the file path follows the expected format.</p>
 */
@Tag("Feature: workspace-data-segments, Property 5: Empty .docx generation produces valid Open XML structure")
class SegmentEmptyDocxPropertyTest {

    private static final Set<String> EXPECTED_ENTRIES = Set.of(
            "[Content_Types].xml",
            "_rels/.rels",
            "word/document.xml"
    );

    private final SegmentService segmentService;
    private final Method generateEmptyDocxMethod;

    SegmentEmptyDocxPropertyTest() throws Exception {
        segmentService = new SegmentService(
                mock(SegmentRepository.class),
                mock(SegmentTagMappingRepository.class),
                mock(SegmentVersionRepository.class),
                mock(SegmentVersionService.class),
                mock(DependencyGraphService.class),
                mock(AuditLogService.class),
                mock(MinioClient.class));

        generateEmptyDocxMethod = SegmentService.class.getDeclaredMethod("generateEmptyDocx");
        generateEmptyDocxMethod.setAccessible(true);
    }

    /**
     * Property 5: Empty .docx generation produces valid Open XML structure.
     *
     * The generated byte[] must be a valid ZIP containing exactly 3 entries,
     * each with well-formed XML content.
     */
    @Property(tries = 100)
    void generateEmptyDocxProducesValidOpenXmlZip(
            @ForAll("segmentNames") String segmentName
    ) throws Exception {
        // Act: invoke the private generateEmptyDocx method
        byte[] docxBytes = (byte[]) generateEmptyDocxMethod.invoke(segmentService);

        // Assert 1: byte[] is non-null and non-empty
        assertNotNull(docxBytes, "Generated docx bytes must not be null");
        assertTrue(docxBytes.length > 0, "Generated docx bytes must not be empty");

        // Assert 2: byte[] is a valid ZIP with exactly 3 entries
        Map<String, byte[]> entries = extractZipEntries(docxBytes);
        assertEquals(EXPECTED_ENTRIES, entries.keySet(),
                "ZIP must contain exactly [Content_Types].xml, _rels/.rels, word/document.xml");

        // Assert 3: each entry contains well-formed XML
        DocumentBuilderFactory dbf = DocumentBuilderFactory.newInstance();
        dbf.setNamespaceAware(true);
        for (Map.Entry<String, byte[]> entry : entries.entrySet()) {
            assertDoesNotThrow(() -> {
                dbf.newDocumentBuilder().parse(new ByteArrayInputStream(entry.getValue()));
            }, "Entry '" + entry.getKey() + "' must contain well-formed XML");
        }
    }

    /**
     * Property 5 (path format): The file path produced by createEmptyDocxSegment
     * follows the pattern segments/{tenantId}/{uuid}_{sanitizedName}.docx
     * where sanitizedName replaces non-alphanumeric characters (except _ and -) with underscores.
     */
    @Property(tries = 100)
    void filePathFollowsExpectedFormat(
            @ForAll("segmentNames") String segmentName,
            @ForAll("tenantIds") Long tenantId
    ) {
        // Replicate the sanitization logic from SegmentService.createEmptyDocxSegment
        String safeName = (segmentName != null
                ? segmentName.replaceAll("[^a-zA-Z0-9_\\-]", "_")
                : "segment");

        String objectName = String.format("segments/%d/%s_%s.docx",
                tenantId, UUID.randomUUID(), safeName);

        // Assert: path starts with segments/{tenantId}/
        assertTrue(objectName.startsWith("segments/" + tenantId + "/"),
                "Path must start with segments/{tenantId}/");

        // Assert: path ends with .docx
        assertTrue(objectName.endsWith(".docx"),
                "Path must end with .docx");

        // Assert: sanitized name contains only allowed characters
        // Extract the part after the UUID_ prefix
        String afterPrefix = objectName.substring(("segments/" + tenantId + "/").length());
        // Format: {uuid}_{safeName}.docx — UUID is 36 chars, then underscore, then safeName.docx
        assertTrue(afterPrefix.length() > 37,
                "Path after prefix must contain UUID + underscore + name");
        String uuidPart = afterPrefix.substring(0, 36);
        assertTrue(uuidPart.matches("[0-9a-f\\-]{36}"),
                "UUID part must be a valid UUID format");
        assertEquals('_', afterPrefix.charAt(36),
                "UUID must be followed by underscore separator");

        String nameAndExt = afterPrefix.substring(37); // safeName.docx
        String nameOnly = nameAndExt.substring(0, nameAndExt.length() - ".docx".length());
        assertTrue(nameOnly.matches("[a-zA-Z0-9_\\-]*"),
                "Sanitized name must contain only alphanumeric, underscore, and hyphen characters, got: " + nameOnly);
    }

    // ── Helpers ──

    private Map<String, byte[]> extractZipEntries(byte[] zipBytes) throws Exception {
        Map<String, byte[]> entries = new LinkedHashMap<>();
        try (ZipInputStream zis = new ZipInputStream(new ByteArrayInputStream(zipBytes))) {
            ZipEntry entry;
            while ((entry = zis.getNextEntry()) != null) {
                entries.put(entry.getName(), zis.readAllBytes());
                zis.closeEntry();
            }
        }
        return entries;
    }

    // ── Generators ──

    @Provide
    Arbitrary<String> segmentNames() {
        return Arbitraries.oneOf(
                // Empty string
                Arbitraries.just(""),
                // Simple ASCII names
                Arbitraries.strings().alpha().numeric().withChars(' ', '-', '_')
                        .ofMinLength(1).ofMaxLength(50),
                // Chinese characters
                Arbitraries.strings()
                        .withCharRange('\u4e00', '\u9fff')
                        .ofMinLength(1).ofMaxLength(30),
                // Special characters that need sanitization
                Arbitraries.of(
                        "合同模板 v2.0",
                        "segment with spaces",
                        "file/path/injection",
                        "name@#$%^&*()",
                        "日本語テスト",
                        "résumé café",
                        "segment_name-valid",
                        "   leading-trailing   ",
                        "a".repeat(200)
                ),
                // Mixed Unicode strings
                Arbitraries.strings()
                        .withCharRange('\u0020', '\ud7ff')
                        .ofMinLength(1).ofMaxLength(100)
        );
    }

    @Provide
    Arbitrary<Long> tenantIds() {
        return Arbitraries.longs().between(1L, 10000L);
    }
}
